name: CI 

on: 
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]

    workflow_dispatch:

  steps: 
  -uses: actions/checkout@v3

  -name: install node package
  -run: npm install

  -name: Build
  -run: npm run build
