name: Build
on:
  push:
    branches: ["main"]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node package
        run: npm install
      - name: build tailwind
        run: npm run build
