name: CI 

on: 
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]

    workflow_dispatch:
jobs:
  steps: 
  -name: install node package
  -run: npm install

  -name: Build
  -run: npm run build
