name: Build

on: 
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]

    workflow_dispatch:
jobs:
  steps: 
    -name: install node package
      run: npm install

  -name: build Tailwind
    run: npm run build
